---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-backend-config
  namespace: backend-comparison
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/comparison_db"
  JWT_SECRET: "your-secret-key-change-in-production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: backend-comparison
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: backend-comparison/node-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-backend-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /metrics
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  namespace: backend-comparison
  labels:
    app: node-backend
spec:
  selector:
    app: node-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-nodeport
  namespace: backend-comparison
  labels:
    app: node-backend
spec:
  selector:
    app: node-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30002
  type: NodePort
