global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python-backend'
    static_configs:
      - targets: ['python-backend-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-backend'
    static_configs:
      - targets: ['node-backend-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter-service:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
