apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb-service:8086
    database: jmeter
    user: jmeter
    password: jmeter
    isDefault: false
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: "5s"
